# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Some non-comprehensive notes
email: paolo@contextswitch.info
description: > # this means to ignore newlines until "baseurl:"
  The idea is to keep some scattered yet useful (maybe sometimes) notes
  related to technology, development and random yet interesting topics.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wildflame.me" # the base hostname & protocol for your site
#twitter_username: 
github_username:  0xb0fh 

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->

# source code base address
source_baseurl: https://github.com/0xb0fh